CLIP:
  pretrained_ckpt: openai/clip-vit-base-patch32
  latent_dim: 768
  freeze: True

Head:
  out_dim: 2 # output dimension of classification head

train:
  n_epochs: 25
  optimizer_name: Adam
  optimizer:
    Adam:
      - lr: 0.001
      - betas: (0.99, 0.999)
    SGD:
      - momentum: 0.9
      - lr: 0.001
  
